name: Monitorar Miniaturas F1

on:
  schedule:
    - cron: '0 13 * * *'  # 13h UTC = 10h horário de Brasília
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chrome e ChromeDriver compatíveis
        uses: browser-actions/setup-chrome@v1

      - name: Instalar xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Rodar o script
        env:
          EMAIL_SENHA_APP: ${{ secrets.EMAIL_SENHA_APP }}
        run: xvfb-run python alerta_mercado_livre.py
