name: Monitorar Miniaturas F1

on:
  schedule:
    - cron: '0 12 * * *'  # 12h UTC = 9h horário de Brasília
  workflow_dispatch:      # permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chrome e ChromeDriver compatíveis
        uses: browser-actions/setup-chrome@v1

      - name: Rodar o script com xvfb
        env:
          EMAIL_SENHA_APP: ${{ secrets.EMAIL_SENHA_APP }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          xvfb-run python alerta_mercado_livre.py
